// TOEIC Vocabulary Database
// Organized by common TOEIC topics with 500 essential words for 700+ TOEIC goal

const vocabularyData = {
    topics: [
        {
            id: 'business-office',
            name: 'Business & Office',
            icon: '💼',
            description: 'Từ vựng văn phòng và kinh doanh',
            words: [
                { word: 'accommodate', type: 'verb', pronunciation: '/əˈkɑːmədeɪt/', meaning: 'Cung cấp chỗ ở, điều chỉnh để phù hợp', example: 'The hotel can accommodate up to 500 guests.' },
                { word: 'agenda', type: 'noun', pronunciation: '/əˈdʒendə/', meaning: 'Chương trình, kế hoạch nghị sự', example: 'What\'s on the agenda for today\'s meeting?' },
                { word: 'allocate', type: 'verb', pronunciation: '/ˈæləkeɪt/', meaning: 'Phân bổ, phân phối', example: 'We need to allocate more resources to this project.' },
                { word: 'analyze', type: 'verb', pronunciation: '/ˈænəlaɪz/', meaning: 'Phân tích', example: 'We need to analyze the market trends.' },
                { word: 'appoint', type: 'verb', pronunciation: '/əˈpɔɪnt/', meaning: 'Bổ nhiệm, chỉ định', example: 'She was appointed as the new CEO.' },
                { word: 'approve', type: 'verb', pronunciation: '/əˈpruːv/', meaning: 'Phê duyệt, chấp thuận', example: 'The board approved the budget proposal.' },
                { word: 'assignment', type: 'noun', pronunciation: '/əˈsaɪnmənt/', meaning: 'Nhiệm vụ, bài tập được giao', example: 'I have to finish this assignment by Friday.' },
                { word: 'assume', type: 'verb', pronunciation: '/əˈsuːm/', meaning: 'Cho rằng, đảm nhận', example: 'He will assume his new position next month.' },
                { word: 'authorize', type: 'verb', pronunciation: '/ˈɔːθəraɪz/', meaning: 'Cho phép, ủy quyền', example: 'Only the manager can authorize this payment.' },
                { word: 'benefit', type: 'noun', pronunciation: '/ˈbenɪfɪt/', meaning: 'Lợi ích, phúc lợi', example: 'The company offers excellent health benefits.' },
                { word: 'budget', type: 'noun', pronunciation: '/ˈbʌdʒɪt/', meaning: 'Ngân sách', example: 'We need to stay within the budget.' },
                { word: 'colleague', type: 'noun', pronunciation: '/ˈkɑːliːɡ/', meaning: 'Đồng nghiệp', example: 'I had lunch with my colleagues today.' },
                { word: 'committee', type: 'noun', pronunciation: '/kəˈmɪti/', meaning: 'Ủy ban, ban tổ chức', example: 'The committee will meet next Tuesday.' },
                { word: 'comply', type: 'verb', pronunciation: '/kəmˈplaɪ/', meaning: 'Tuân thủ, chấp hành', example: 'All employees must comply with company policies.' },
                { word: 'conduct', type: 'verb', pronunciation: '/kənˈdʌkt/', meaning: 'Tiến hành, thực hiện', example: 'We will conduct a survey next month.' },
                { word: 'conference', type: 'noun', pronunciation: '/ˈkɑːnfərəns/', meaning: 'Hội nghị', example: 'She is attending a conference in New York.' },
                { word: 'confidential', type: 'adj', pronunciation: '/ˌkɑːnfɪˈdenʃl/', meaning: 'Bí mật, mật', example: 'This information is strictly confidential.' },
                { word: 'confirm', type: 'verb', pronunciation: '/kənˈfɜːrm/', meaning: 'Xác nhận', example: 'Please confirm your attendance by email.' },
                { word: 'contract', type: 'noun', pronunciation: '/ˈkɑːntrækt/', meaning: 'Hợp đồng', example: 'We signed a two-year contract.' },
                { word: 'deadline', type: 'noun', pronunciation: '/ˈdedlaɪn/', meaning: 'Hạn chót', example: 'The deadline for this project is next Friday.' },
                { word: 'delegate', type: 'verb', pronunciation: '/ˈdelɪɡeɪt/', meaning: 'Ủy quyền, giao phó', example: 'You need to delegate tasks more effectively.' },
                { word: 'department', type: 'noun', pronunciation: '/dɪˈpɑːrtmənt/', meaning: 'Bộ phận, phòng ban', example: 'She works in the marketing department.' },
                { word: 'determine', type: 'verb', pronunciation: '/dɪˈtɜːrmɪn/', meaning: 'Xác định, quyết định', example: 'We will determine the budget next week.' },
                { word: 'director', type: 'noun', pronunciation: '/dəˈrektər/', meaning: 'Giám đốc', example: 'The director called an urgent meeting.' },
                { word: 'discuss', type: 'verb', pronunciation: '/dɪˈskʌs/', meaning: 'Thảo luận', example: 'Let\'s discuss this matter in detail.' },
                { word: 'distribute', type: 'verb', pronunciation: '/dɪˈstrɪbjuːt/', meaning: 'Phân phối, phân phát', example: 'Please distribute the reports to all managers.' },
                { word: 'document', type: 'noun', pronunciation: '/ˈdɑːkjumənt/', meaning: 'Tài liệu, văn bản', example: 'All documents must be signed.' },
                { word: 'efficient', type: 'adj', pronunciation: '/ɪˈfɪʃnt/', meaning: 'Hiệu quả', example: 'We need a more efficient system.' },
                { word: 'employee', type: 'noun', pronunciation: '/ɪmˈplɔɪiː/', meaning: 'Nhân viên', example: 'All employees will receive a bonus.' },
                { word: 'establish', type: 'verb', pronunciation: '/ɪˈstæblɪʃ/', meaning: 'Thiết lập, thành lập', example: 'The company was established in 1990.' },
                { word: 'evaluate', type: 'verb', pronunciation: '/ɪˈvæljueɪt/', meaning: 'Đánh giá', example: 'We need to evaluate employee performance.' },
                { word: 'executive', type: 'noun', pronunciation: '/ɪɡˈzekjətɪv/', meaning: 'Giám đốc điều hành', example: 'The executive team made the final decision.' },
                { word: 'facility', type: 'noun', pronunciation: '/fəˈsɪləti/', meaning: 'Cơ sở vật chất', example: 'The office has excellent facilities.' },
                { word: 'file', type: 'noun', pronunciation: '/faɪl/', meaning: 'Hồ sơ, tập tin', example: 'Please file these documents alphabetically.' },
                { word: 'implement', type: 'verb', pronunciation: '/ˈɪmplɪment/', meaning: 'Thực hiện, triển khai', example: 'We will implement the new policy next month.' },
                { word: 'increase', type: 'verb', pronunciation: '/ɪnˈkriːs/', meaning: 'Tăng, gia tăng', example: 'Sales increased by 20% this quarter.' },
                { word: 'inform', type: 'verb', pronunciation: '/ɪnˈfɔːrm/', meaning: 'Thông báo, báo cho biết', example: 'Please inform all staff about the changes.' },
                { word: 'issue', type: 'noun', pronunciation: '/ˈɪʃuː/', meaning: 'Vấn đề', example: 'We need to address this issue immediately.' },
                { word: 'manage', type: 'verb', pronunciation: '/ˈmænɪdʒ/', meaning: 'Quản lý', example: 'She manages a team of 15 people.' },
                { word: 'manager', type: 'noun', pronunciation: '/ˈmænɪdʒər/', meaning: 'Quản lý, người quản lý', example: 'The manager approved the request.' },
                { word: 'memo', type: 'noun', pronunciation: '/ˈmemoʊ/', meaning: 'Bản ghi nhớ', example: 'Did you read the memo about the new policy?' },
                { word: 'objective', type: 'noun', pronunciation: '/əbˈdʒektɪv/', meaning: 'Mục tiêu', example: 'Our main objective is customer satisfaction.' },
                { word: 'organize', type: 'verb', pronunciation: '/ˈɔːrɡənaɪz/', meaning: 'Tổ chức, sắp xếp', example: 'She organized the company event.' },
                { word: 'policy', type: 'noun', pronunciation: '/ˈpɑːləsi/', meaning: 'Chính sách', example: 'The new policy will take effect next month.' },
                { word: 'procedure', type: 'noun', pronunciation: '/prəˈsiːdʒər/', meaning: 'Quy trình, thủ tục', example: 'Follow the safety procedures at all times.' },
                { word: 'project', type: 'noun', pronunciation: '/ˈprɑːdʒekt/', meaning: 'Dự án', example: 'The project will be completed in six months.' },
                { word: 'staff', type: 'noun', pronunciation: '/stæf/', meaning: 'Nhân viên, đội ngũ', example: 'All staff members attended the training.' },
                { word: 'supervise', type: 'verb', pronunciation: '/ˈsuːpərvaɪz/', meaning: 'Giám sát', example: 'He supervises the production department.' },
                { word: 'task', type: 'noun', pronunciation: '/tæsk/', meaning: 'Nhiệm vụ, công việc', example: 'Complete all assigned tasks by Friday.' }
            ]
        },
        {
            id: 'finance-banking',
            name: 'Finance & Banking',
            icon: '💰',
            description: 'Từ vựng tài chính và ngân hàng',
            words: [
                { word: 'account', type: 'noun', pronunciation: '/əˈkaʊnt/', meaning: 'Tài khoản', example: 'I need to check my bank account balance.' },
                { word: 'balance', type: 'noun', pronunciation: '/ˈbæləns/', meaning: 'Số dư, cân bằng', example: 'What is your current account balance?' },
                { word: 'charge', type: 'verb', pronunciation: '/tʃɑːrdʒ/', meaning: 'Tính phí, thu phí', example: 'The bank charges a monthly fee.' },
                { word: 'credit', type: 'noun', pronunciation: '/ˈkredɪt/', meaning: 'Tín dụng, tiền gửi', example: 'You can pay by credit card.' },
                { word: 'currency', type: 'noun', pronunciation: '/ˈkɜːrənsi/', meaning: 'Tiền tệ', example: 'What currency do you accept?' },
                { word: 'debt', type: 'noun', pronunciation: '/det/', meaning: 'Nợ, món nợ', example: 'The company has a lot of debt.' },
                { word: 'deposit', type: 'verb', pronunciation: '/dɪˈpɑːzɪt/', meaning: 'Gửi tiền, đặt cọc', example: 'I need to deposit this check.' },
                { word: 'dividend', type: 'noun', pronunciation: '/ˈdɪvɪdend/', meaning: 'Cổ tức', example: 'Shareholders will receive dividends quarterly.' },
                { word: 'expense', type: 'noun', pronunciation: '/ɪkˈspens/', meaning: 'Chi phí, khoản chi', example: 'Travel expenses will be reimbursed.' },
                { word: 'fee', type: 'noun', pronunciation: '/fiː/', meaning: 'Phí, lệ phí', example: 'There is a processing fee for this service.' },
                { word: 'finance', type: 'noun', pronunciation: '/ˈfaɪnæns/', meaning: 'Tài chính', example: 'She works in the finance department.' },
                { word: 'fund', type: 'noun', pronunciation: '/fʌnd/', meaning: 'Quỹ, vốn', example: 'The project needs more funds.' },
                { word: 'income', type: 'noun', pronunciation: '/ˈɪnkʌm/', meaning: 'Thu nhập', example: 'What is your annual income?' },
                { word: 'interest', type: 'noun', pronunciation: '/ˈɪntrəst/', meaning: 'Lãi suất, tiền lãi', example: 'The interest rate is 5% per year.' },
                { word: 'invest', type: 'verb', pronunciation: '/ɪnˈvest/', meaning: 'Đầu tư', example: 'I want to invest in stocks.' },
                { word: 'loan', type: 'noun', pronunciation: '/loʊn/', meaning: 'Khoản vay', example: 'He applied for a home loan.' },
                { word: 'payment', type: 'noun', pronunciation: '/ˈpeɪmənt/', meaning: 'Thanh toán, khoản thanh toán', example: 'The payment is due on the 1st of each month.' },
                { word: 'profit', type: 'noun', pronunciation: '/ˈprɑːfɪt/', meaning: 'Lợi nhuận', example: 'The company made a huge profit last year.' },
                { word: 'refund', type: 'noun', pronunciation: '/ˈriːfʌnd/', meaning: 'Hoàn tiền', example: 'You can get a full refund within 30 days.' },
                { word: 'withdraw', type: 'verb', pronunciation: '/wɪðˈdrɔː/', meaning: 'Rút tiền', example: 'I need to withdraw some cash from the ATM.' },
                { word: 'asset', type: 'noun', pronunciation: '/ˈæset/', meaning: 'Tài sản', example: 'Real estate is a valuable asset.' },
                { word: 'audit', type: 'noun', pronunciation: '/ˈɔːdɪt/', meaning: 'Kiểm toán', example: 'The company underwent a financial audit.' },
                { word: 'bank', type: 'noun', pronunciation: '/bæŋk/', meaning: 'Ngân hàng', example: 'I need to go to the bank today.' },
                { word: 'bankrupt', type: 'adj', pronunciation: '/ˈbæŋkrʌpt/', meaning: 'Phá sản', example: 'The company went bankrupt last year.' },
                { word: 'bill', type: 'noun', pronunciation: '/bɪl/', meaning: 'Hóa đơn, giấy bạc', example: 'Please pay the bill by the end of the month.' },
                { word: 'bond', type: 'noun', pronunciation: '/bɑːnd/', meaning: 'Trái phiếu', example: 'Government bonds are considered safe investments.' },
                { word: 'budget', type: 'verb', pronunciation: '/ˈbʌdʒɪt/', meaning: 'Lập ngân sách', example: 'We need to budget carefully this year.' },
                { word: 'capital', type: 'noun', pronunciation: '/ˈkæpɪtl/', meaning: 'Vốn, thủ đô', example: 'The business needs more capital to expand.' },
                { word: 'cash', type: 'noun', pronunciation: '/kæʃ/', meaning: 'Tiền mặt', example: 'Do you accept cash or card?' },
                { word: 'check', type: 'noun', pronunciation: '/tʃek/', meaning: 'Séc', example: 'I wrote a check for the rent.' },
                { word: 'claim', type: 'verb', pronunciation: '/kleɪm/', meaning: 'Yêu cầu bồi thường', example: 'You can claim on your insurance.' },
                { word: 'commission', type: 'noun', pronunciation: '/kəˈmɪʃn/', meaning: 'Hoa hồng', example: 'Salespeople earn a commission on each sale.' },
                { word: 'compound', type: 'verb', pronunciation: '/kəmˈpaʊnd/', meaning: 'Gộp lãi, tổng hợp', example: 'Interest compounds quarterly.' },
                { word: 'customer', type: 'noun', pronunciation: '/ˈkʌstəmər/', meaning: 'Khách hàng', example: 'We value our customers.' },
                { word: 'deduct', type: 'verb', pronunciation: '/dɪˈdʌkt/', meaning: 'Khấu trừ, trừ đi', example: 'Taxes are deducted from your salary.' },
                { word: 'deficit', type: 'noun', pronunciation: '/ˈdefɪsɪt/', meaning: 'Thâm hụt', example: 'The company reported a budget deficit.' },
                { word: 'economy', type: 'noun', pronunciation: '/ɪˈkɑːnəmi/', meaning: 'Nền kinh tế', example: 'The economy is growing steadily.' },
                { word: 'equity', type: 'noun', pronunciation: '/ˈekwəti/', meaning: 'Vốn chủ sở hữu', example: 'Shareholders\' equity increased this quarter.' },
                { word: 'estimate', type: 'verb', pronunciation: '/ˈestɪmeɪt/', meaning: 'Ước tính', example: 'We estimate the cost at $10,000.' },
                { word: 'exchange', type: 'noun', pronunciation: '/ɪksˈtʃeɪndʒ/', meaning: 'Trao đổi, sàn giao dịch', example: 'The stock exchange opens at 9 AM.' },
                { word: 'financial', type: 'adj', pronunciation: '/faɪˈnænʃl/', meaning: 'Thuộc về tài chính', example: 'We need financial advice.' },
                { word: 'fiscal', type: 'adj', pronunciation: '/ˈfɪskl/', meaning: 'Thuộc về tài khóa', example: 'The fiscal year ends in December.' },
                { word: 'inflation', type: 'noun', pronunciation: '/ɪnˈfleɪʃn/', meaning: 'Lạm phát', example: 'Inflation is affecting consumer prices.' },
                { word: 'installment', type: 'noun', pronunciation: '/ɪnˈstɔːlmənt/', meaning: 'Trả góp', example: 'You can pay in monthly installments.' },
                { word: 'insurance', type: 'noun', pronunciation: '/ɪnˈʃʊrəns/', meaning: 'Bảo hiểm', example: 'Do you have car insurance?' },
                { word: 'invoice', type: 'noun', pronunciation: '/ˈɪnvɔɪs/', meaning: 'Hóa đơn', example: 'Please send me the invoice.' },
                { word: 'liability', type: 'noun', pronunciation: '/ˌlaɪəˈbɪləti/', meaning: 'Nợ phải trả, trách nhiệm pháp lý', example: 'The company has significant liabilities.' },
                { word: 'mortgage', type: 'noun', pronunciation: '/ˈmɔːrɡɪdʒ/', meaning: 'Thế chấp, cho vay mua nhà', example: 'They took out a mortgage to buy a house.' },
                { word: 'revenue', type: 'noun', pronunciation: '/ˈrevənuː/', meaning: 'Doanh thu', example: 'Revenue increased by 15% this year.' }
            ]
        },
        {
            id: 'travel-transportation',
            name: 'Travel & Transportation',
            icon: '✈️',
            description: 'Từ vựng du lịch và giao thông',
            words: [
                { word: 'accommodation', type: 'noun', pronunciation: '/əˌkɑːməˈdeɪʃn/', meaning: 'Chỗ ở, nơi nghỉ', example: 'We need to book accommodation for our trip.' },
                { word: 'arrival', type: 'noun', pronunciation: '/əˈraɪvl/', meaning: 'Sự đến, sự tới nơi', example: 'Please confirm your arrival time.' },
                { word: 'baggage', type: 'noun', pronunciation: '/ˈbæɡɪdʒ/', meaning: 'Hành lý', example: 'Where can I collect my baggage?' },
                { word: 'boarding', type: 'noun', pronunciation: '/ˈbɔːrdɪŋ/', meaning: 'Lên tàu, lên máy bay', example: 'Boarding will begin at 3:00 PM.' },
                { word: 'commute', type: 'verb', pronunciation: '/kəˈmjuːt/', meaning: 'Đi lại (đi làm)', example: 'I commute to work by train.' },
                { word: 'delay', type: 'noun', pronunciation: '/dɪˈleɪ/', meaning: 'Sự chậm trễ', example: 'There was a two-hour delay due to bad weather.' },
                { word: 'departure', type: 'noun', pronunciation: '/dɪˈpɑːrtʃər/', meaning: 'Sự khởi hành', example: 'The departure time is 6:00 AM.' },
                { word: 'destination', type: 'noun', pronunciation: '/ˌdestɪˈneɪʃn/', meaning: 'Điểm đến', example: 'What is your final destination?' },
                { word: 'fare', type: 'noun', pronunciation: '/fer/', meaning: 'Giá vé, cước phí', example: 'The taxi fare was very expensive.' },
                { word: 'itinerary', type: 'noun', pronunciation: '/aɪˈtɪnəreri/', meaning: 'Lịch trình, hành trình', example: 'Here is your travel itinerary.' },
                { word: 'luggage', type: 'noun', pronunciation: '/ˈlʌɡɪdʒ/', meaning: 'Hành lý', example: 'Don\'t forget your hand luggage.' },
                { word: 'passenger', type: 'noun', pronunciation: '/ˈpæsɪndʒər/', meaning: 'Hành khách', example: 'All passengers must fasten their seatbelts.' },
                { word: 'reservation', type: 'noun', pronunciation: '/ˌrezərˈveɪʃn/', meaning: 'Đặt chỗ trước', example: 'I have a reservation for two people.' },
                { word: 'route', type: 'noun', pronunciation: '/ruːt/', meaning: 'Tuyến đường, lộ trình', example: 'This is the fastest route to the airport.' },
                { word: 'schedule', type: 'noun', pronunciation: '/ˈskedʒuːl/', meaning: 'Lịch trình, thời gian biểu', example: 'Check the train schedule online.' },
                { word: 'terminal', type: 'noun', pronunciation: '/ˈtɜːrmɪnl/', meaning: 'Nhà ga, sân bay', example: 'My flight departs from Terminal 3.' },
                { word: 'ticket', type: 'noun', pronunciation: '/ˈtɪkɪt/', meaning: 'Vé', example: 'I bought a round-trip ticket.' },
                { word: 'transfer', type: 'verb', pronunciation: '/trænsˈfɜːr/', meaning: 'Chuyển, đổi', example: 'You need to transfer at the next station.' },
                { word: 'transit', type: 'noun', pronunciation: '/ˈtrænsɪt/', meaning: 'Quá cảnh, vận chuyển', example: 'We are in transit to Tokyo.' },
                { word: 'vehicle', type: 'noun', pronunciation: '/ˈviːəkl/', meaning: 'Phương tiện', example: 'What type of vehicle do you drive?' },
                { word: 'aircraft', type: 'noun', pronunciation: '/ˈerkræft/', meaning: 'Máy bay', example: 'The aircraft will depart at 6 PM.' },
                { word: 'aisle', type: 'noun', pronunciation: '/aɪl/', meaning: 'Lối đi (giữa các hàng ghế)', example: 'I prefer an aisle seat.' },
                { word: 'cancellation', type: 'noun', pronunciation: '/ˌkænsəˈleɪʃn/', meaning: 'Sự hủy bỏ', example: 'Flight cancellations are common in winter.' },
                { word: 'cargo', type: 'noun', pronunciation: '/ˈkɑːrɡoʊ/', meaning: 'Hàng hóa vận chuyển', example: 'The cargo ship left the port.' },
                { word: 'connecting', type: 'adj', pronunciation: '/kəˈnektɪŋ/', meaning: 'Nối chuyến', example: 'I have a connecting flight in Dubai.' },
                { word: 'customs', type: 'noun', pronunciation: '/ˈkʌstəmz/', meaning: 'Hải quan', example: 'Please proceed to customs.' },
                { word: 'detour', type: 'noun', pronunciation: '/ˈdiːtʊr/', meaning: 'Đường vòng', example: 'We had to take a detour due to road construction.' },
                { word: 'domestic', type: 'adj', pronunciation: '/dəˈmestɪk/', meaning: 'Trong nước', example: 'This is a domestic flight.' },
                { word: 'embark', type: 'verb', pronunciation: '/ɪmˈbɑːrk/', meaning: 'Lên tàu/máy bay', example: 'Passengers will embark at gate 12.' },
                { word: 'expedition', type: 'noun', pronunciation: '/ˌekspəˈdɪʃn/', meaning: 'Chuyến thám hiểm', example: 'They went on an expedition to Antarctica.' },
                { word: 'flight', type: 'noun', pronunciation: '/flaɪt/', meaning: 'Chuyến bay', example: 'My flight was delayed.' },
                { word: 'frequent', type: 'adj', pronunciation: '/ˈfriːkwənt/', meaning: 'Thường xuyên', example: 'I\'m a frequent flyer.' },
                { word: 'gate', type: 'noun', pronunciation: '/ɡeɪt/', meaning: 'Cổng (sân bay)', example: 'Boarding at gate 15.' },
                { word: 'guidebook', type: 'noun', pronunciation: '/ˈɡaɪdbʊk/', meaning: 'Sách hướng dẫn du lịch', example: 'I bought a guidebook for Paris.' },
                { word: 'highway', type: 'noun', pronunciation: '/ˈhaɪweɪ/', meaning: 'Đường cao tốc', example: 'Take the highway to the airport.' },
                { word: 'journey', type: 'noun', pronunciation: '/ˈdʒɜːrni/', meaning: 'Cuộc hành trình', example: 'Have a safe journey!' },
                { word: 'landmark', type: 'noun', pronunciation: '/ˈlændmɑːrk/', meaning: 'Địa danh nổi tiếng', example: 'The Eiffel Tower is a famous landmark.' },
                { word: 'navigate', type: 'verb', pronunciation: '/ˈnævɪɡeɪt/', meaning: 'Định hướng, điều khiển', example: 'Use GPS to navigate to the hotel.' },
                { word: 'overseas', type: 'adj', pronunciation: '/ˌoʊvərˈsiːz/', meaning: 'Ở nước ngoài', example: 'She works overseas.' },
                { word: 'platform', type: 'noun', pronunciation: '/ˈplætfɔːrm/', meaning: 'Sân ga', example: 'The train departs from platform 3.' },
                { word: 'runway', type: 'noun', pronunciation: '/ˈrʌnweɪ/', meaning: 'Đường băng', example: 'The plane is on the runway.' },
                { word: 'sightseeing', type: 'noun', pronunciation: '/ˈsaɪtsiːɪŋ/', meaning: 'Tham quan', example: 'We spent the day sightseeing.' },
                { word: 'stopover', type: 'noun', pronunciation: '/ˈstɑːpoʊvər/', meaning: 'Điểm dừng chân', example: 'We have a stopover in Singapore.' },
                { word: 'tour', type: 'noun', pronunciation: '/tʊr/', meaning: 'Chuyến du lịch', example: 'We booked a city tour.' },
                { word: 'tourist', type: 'noun', pronunciation: '/ˈtʊrɪst/', meaning: 'Du khách', example: 'The city attracts many tourists.' },
                { word: 'traveler', type: 'noun', pronunciation: '/ˈtrævlər/', meaning: 'Du khách, người đi du lịch', example: 'Business travelers often use this airline.' },
                { word: 'trip', type: 'noun', pronunciation: '/trɪp/', meaning: 'Chuyến đi', example: 'How was your trip?' },
                { word: 'voyage', type: 'noun', pronunciation: '/ˈvɔɪɪdʒ/', meaning: 'Chuyến đi biển dài', example: 'They embarked on a long voyage.' },
                { word: 'wheelchair', type: 'noun', pronunciation: '/ˈwiːltʃer/', meaning: 'Xe lăn', example: 'Wheelchair assistance is available.' }
            ]
        },
        {
            id: 'dining-restaurant',
            name: 'Dining & Restaurant',
            icon: '🍽️',
            description: 'Từ vựng nhà hàng và ẩm thực',
            words: [
                { word: 'appetizer', type: 'noun', pronunciation: '/ˈæpɪtaɪzər/', meaning: 'Món khai vị', example: 'Would you like an appetizer before the main course?' },
                { word: 'beverage', type: 'noun', pronunciation: '/ˈbevərɪdʒ/', meaning: 'Đồ uống', example: 'What beverage would you like?' },
                { word: 'cuisine', type: 'noun', pronunciation: '/kwɪˈziːn/', meaning: 'Ẩm thực', example: 'I love Italian cuisine.' },
                { word: 'dessert', type: 'noun', pronunciation: '/dɪˈzɜːrt/', meaning: 'Món tráng miệng', example: 'Would you like to see the dessert menu?' },
                { word: 'dining', type: 'noun', pronunciation: '/ˈdaɪnɪŋ/', meaning: 'Ăn uống, bữa ăn', example: 'The hotel has fine dining options.' },
                { word: 'dish', type: 'noun', pronunciation: '/dɪʃ/', meaning: 'Món ăn', example: 'This dish is very popular.' },
                { word: 'ingredient', type: 'noun', pronunciation: '/ɪnˈɡriːdiənt/', meaning: 'Nguyên liệu', example: 'What are the main ingredients in this dish?' },
                { word: 'menu', type: 'noun', pronunciation: '/ˈmenjuː/', meaning: 'Thực đơn', example: 'Can I see the menu, please?' },
                { word: 'order', type: 'verb', pronunciation: '/ˈɔːrdər/', meaning: 'Gọi món, đặt hàng', example: 'Are you ready to order?' },
                { word: 'portion', type: 'noun', pronunciation: '/ˈpɔːrʃn/', meaning: 'Phần ăn', example: 'The portions here are very generous.' },
                { word: 'recommend', type: 'verb', pronunciation: '/ˌrekəˈmend/', meaning: 'Giới thiệu, khuyên', example: 'What do you recommend?' },
                { word: 'recipe', type: 'noun', pronunciation: '/ˈresəpi/', meaning: 'Công thức nấu ăn', example: 'Do you have the recipe for this cake?' },
                { word: 'reserve', type: 'verb', pronunciation: '/rɪˈzɜːrv/', meaning: 'Đặt chỗ trước', example: 'I would like to reserve a table for four.' },
                { word: 'server', type: 'noun', pronunciation: '/ˈsɜːrvər/', meaning: 'Người phục vụ', example: 'Our server was very friendly.' },
                { word: 'serve', type: 'verb', pronunciation: '/sɜːrv/', meaning: 'Phục vụ', example: 'Dinner is served from 6 PM.' },
                { word: 'specialty', type: 'noun', pronunciation: '/ˈspeʃəlti/', meaning: 'Đặc sản, món đặc biệt', example: 'What is the specialty of this restaurant?' },
                { word: 'taste', type: 'verb', pronunciation: '/teɪst/', meaning: 'Nếm, có vị', example: 'Would you like to taste the wine?' },
                { word: 'tip', type: 'noun', pronunciation: '/tɪp/', meaning: 'Tiền boa', example: 'Don\'t forget to leave a tip.' },
                { word: 'vegetarian', type: 'adj', pronunciation: '/ˌvedʒəˈteriən/', meaning: 'Ăn chay', example: 'Do you have vegetarian options?' },
                { word: 'waiter', type: 'noun', pronunciation: '/ˈweɪtər/', meaning: 'Bồi bàn', example: 'The waiter brought our food quickly.' },
                { word: 'waitress', type: 'noun', pronunciation: '/ˈweɪtrəs/', meaning: 'Bồi bàn (nữ)', example: 'The waitress was very helpful.' },
                { word: 'bland', type: 'adj', pronunciation: '/blænd/', meaning: 'Nhạt nhẽo', example: 'The soup tastes bland.' },
                { word: 'gluten-free', type: 'adj', pronunciation: '/ˈɡluːtn friː/', meaning: 'Không chứa gluten', example: 'Is this gluten-free?' },
                { word: 'bill', type: 'noun', pronunciation: '/bɪl/', meaning: 'Hóa đơn thanh toán', example: 'Can I have the bill, please?' },
                { word: 'chef', type: 'noun', pronunciation: '/ʃef/', meaning: 'Đầu bếp', example: 'The chef prepared a special dish.' },
                { word: 'delicious', type: 'adj', pronunciation: '/dɪˈlɪʃəs/', meaning: 'Ngon', example: 'The food was delicious!' },
                { word: 'fresh', type: 'adj', pronunciation: '/freʃ/', meaning: 'Tươi', example: 'The fish is fresh from the market.' },
                { word: 'takeout', type: 'noun', pronunciation: '/ˈteɪkaʊt/', meaning: 'Đồ ăn mang về', example: 'We ordered takeout for dinner.' },
                { word: 'delivery', type: 'noun', pronunciation: '/dɪˈlɪvəri/', meaning: 'Giao hàng', example: 'Free delivery for orders over $20.' },
                { word: 'seasoning', type: 'noun', pronunciation: '/ˈsiːzənɪŋ/', meaning: 'Gia vị', example: 'Add more seasoning if needed.' },
                { word: 'catering', type: 'noun', pronunciation: '/ˈkeɪtərɪŋ/', meaning: 'Dịch vụ phục vụ tiệc', example: 'We provide catering services.' },
                { word: 'venue', type: 'noun', pronunciation: '/ˈvenjuː/', meaning: 'Địa điểm tổ chức', example: 'This is a great venue for events.' },
                { word: 'spicy', type: 'adj', pronunciation: '/ˈspaɪsi/', meaning: 'Cay', example: 'This curry is very spicy.' },
                { word: 'table', type: 'noun', pronunciation: '/ˈteɪbl/', meaning: 'Bàn ăn', example: 'A table for two, please.' },
                { word: 'reservation', type: 'noun', pronunciation: '/ˌrezərˈveɪʃn/', meaning: 'Đặt bàn trước', example: 'Do you have a reservation?' },
                { word: 'complimentary', type: 'adj', pronunciation: '/ˌkɑːmplɪˈmentəri/', meaning: 'Miễn phí (dịch vụ)', example: 'Coffee is complimentary.' },
                { word: 'buffet', type: 'noun', pronunciation: '/bəˈfeɪ/', meaning: 'Tiệc buffet', example: 'We offer a breakfast buffet.' },
                { word: 'reservation', type: 'noun', pronunciation: '/ˌrezərˈveɪʃn/', meaning: 'Sự đặt trước', example: 'I\'d like to make a reservation.' },
                { word: 'meal', type: 'noun', pronunciation: '/miːl/', meaning: 'Bữa ăn', example: 'Enjoy your meal!' },
                { word: 'entree', type: 'noun', pronunciation: '/ˈɑːntreɪ/', meaning: 'Món chính', example: 'What would you like for your entree?' },
                { word: 'side', type: 'noun', pronunciation: '/saɪd/', meaning: 'Món phụ', example: 'Would you like fries as a side?' },
                { word: 'flavour', type: 'noun', pronunciation: '/ˈfleɪvər/', meaning: 'Hương vị', example: 'This dish has a unique flavour.' },
                { word: 'organic', type: 'adj', pronunciation: '/ɔːrˈɡænɪk/', meaning: 'Hữu cơ', example: 'We serve organic vegetables.' },
                { word: 'takeout', type: 'noun', pronunciation: '/ˈteɪkaʊt/', meaning: 'Đồ ăn mang đi', example: 'We also offer takeout service.' },
                { word: 'delivery', type: 'noun', pronunciation: '/dɪˈlɪvəri/', meaning: 'Giao hàng tận nơi', example: 'Free delivery for orders over $20.' },
                { word: 'catering', type: 'noun', pronunciation: '/ˈkeɪtərɪŋ/', meaning: 'Phục vụ tiệc', example: 'We provide catering services.' },
                { word: 'host', type: 'noun', pronunciation: '/hoʊst/', meaning: 'Người tiếp vị trí', example: 'Please wait to be seated by the host.' },
                { word: 'dine', type: 'verb', pronunciation: '/daɪn/', meaning: 'Dùng bữa', example: 'We dine out every Friday.' },
                { word: 'seasoning', type: 'noun', pronunciation: '/ˈsiːzənɪŋ/', meaning: 'Gia vị', example: 'Add seasoning to taste.' },
                { word: 'gourmet', type: 'adj', pronunciation: '/ɡʊrˈmeɪ/', meaning: 'Cao cấp (món ăn)', example: 'This is a gourmet restaurant.' },
                { word: 'tender', type: 'adj', pronunciation: '/ˈtendər/', meaning: 'Mềm (thịt)', example: 'The steak is very tender.' },
                { word: 'rare', type: 'adj', pronunciation: '/rer/', meaning: 'Tái (độ chín)', example: 'I\'d like my steak rare, please.' },
                { word: 'medium', type: 'adj', pronunciation: '/ˈmiːdiəm/', meaning: 'Vừa (độ chín)', example: 'Cook the burger medium.' },
                { word: 'well-done', type: 'adj', pronunciation: '/ˌwel ˈdʌn/', meaning: 'Chín kỹ', example: 'I prefer my meat well-done.' },
                { word: 'al dente', type: 'adj', pronunciation: '/ˌæl ˈdenteɪ/', meaning: 'Vừa chín (mì)', example: 'Cook the pasta al dente.' },
                { word: 'savory', type: 'adj', pronunciation: '/ˈseɪvəri/', meaning: 'Mặn (không ngọt)', example: 'I prefer savory over sweet.' }
            ]
        },
        {
            id: 'shopping-retail',
            name: 'Shopping & Retail',
            icon: '🛍️',
            description: 'Từ vựng mua sắm và bán lẻ',
            words: [
                { word: 'bargain', type: 'noun', pronunciation: '/ˈbɑːrɡən/', meaning: 'Món hời, mua rẻ', example: 'I got a great bargain on this jacket.' },
                { word: 'cashier', type: 'noun', pronunciation: '/kæˈʃɪr/', meaning: 'Thu ngân', example: 'Please pay at the cashier.' },
                { word: 'checkout', type: 'noun', pronunciation: '/ˈtʃekaʊt/', meaning: 'Quầy thanh toán', example: 'There are long lines at the checkout.' },
                { word: 'customer', type: 'noun', pronunciation: '/ˈkʌstəmər/', meaning: 'Khách hàng', example: 'The customer is always right.' },
                { word: 'discount', type: 'noun', pronunciation: '/ˈdɪskaʊnt/', meaning: 'Giảm giá', example: 'There is a 20% discount on all items.' },
                { word: 'exchange', type: 'verb', pronunciation: '/ɪksˈtʃeɪndʒ/', meaning: 'Đổi, trao đổi', example: 'Can I exchange this for a different size?' },
                { word: 'guarantee', type: 'noun', pronunciation: '/ˌɡærənˈtiː/', meaning: 'Bảo hành, đảm bảo', example: 'This product comes with a one-year guarantee.' },
                { word: 'item', type: 'noun', pronunciation: '/ˈaɪtəm/', meaning: 'Món đồ, hàng hóa', example: 'How many items do you have?' },
                { word: 'price', type: 'noun', pronunciation: '/praɪs/', meaning: 'Giá cả', example: 'What is the price of this shirt?' },
                { word: 'purchase', type: 'verb', pronunciation: '/ˈpɜːrtʃəs/', meaning: 'Mua, sự mua', example: 'I would like to purchase this item.' },
                { word: 'receipt', type: 'noun', pronunciation: '/rɪˈsiːt/', meaning: 'Hóa đơn, biên lai', example: 'Please keep your receipt.' },
                { word: 'refund', type: 'verb', pronunciation: '/ˈriːfʌnd/', meaning: 'Hoàn tiền', example: 'Can I get a refund for this?' },
                { word: 'retail', type: 'noun', pronunciation: '/ˈriːteɪl/', meaning: 'Bán lẻ', example: 'She works in retail.' },
                { word: 'sale', type: 'noun', pronunciation: '/seɪl/', meaning: 'Đợt giảm giá', example: 'There is a big sale this weekend.' },
                { word: 'shopkeeper', type: 'noun', pronunciation: '/ˈʃɑːpkiːpər/', meaning: 'Chủ cửa hàng', example: 'The shopkeeper was very helpful.' },
                { word: 'stock', type: 'noun', pronunciation: '/stɑːk/', meaning: 'Hàng tồn kho', example: 'This item is out of stock.' },
                { word: 'store', type: 'noun', pronunciation: '/stɔːr/', meaning: 'Cửa hàng', example: 'The store opens at 9 AM.' },
                { word: 'tax', type: 'noun', pronunciation: '/tæks/', meaning: 'Thuế', example: 'The price includes tax.' },
                { word: 'value', type: 'noun', pronunciation: '/ˈvæljuː/', meaning: 'Giá trị', example: 'This product offers excellent value for money.' },
                { word: 'warranty', type: 'noun', pronunciation: '/ˈwɔːrənti/', meaning: 'Bảo hành', example: 'Does it come with a warranty?' },
                { word: 'affordable', type: 'adj', pronunciation: '/əˈfɔːrdəbl/', meaning: 'Phải chăng, có khả năng mua được', example: 'The prices are very affordable.' },
                { word: 'aisle', type: 'noun', pronunciation: '/aɪl/', meaning: 'Lối đi trong cửa hàng', example: 'The milk is in aisle 3.' },
                { word: 'brand', type: 'noun', pronunciation: '/brænd/', meaning: 'Nhãn hiệu', example: 'What brand do you prefer?' },
                { word: 'browse', type: 'verb', pronunciation: '/braʊz/', meaning: 'Xem qua, dạo', example: 'Feel free to browse.' },
                { word: 'cart', type: 'noun', pronunciation: '/kɑːrt/', meaning: 'Xe đẩy', example: 'Get a shopping cart.' },
                { word: 'clearance', type: 'noun', pronunciation: '/ˈklɪrəns/', meaning: 'Hàng thanh lý', example: 'Clearance items are 50% off.' },
                { word: 'consumer', type: 'noun', pronunciation: '/kənˈsuːmər/', meaning: 'Người tiêu dùng', example: 'Consumer spending increased.' },
                { word: 'coupon', type: 'noun', pronunciation: '/ˈkuːpɑːn/', meaning: 'Phiếu giảm giá', example: 'I have a coupon for 20% off.' },
                { word: 'deal', type: 'noun', pronunciation: '/diːl/', meaning: 'Món hời', example: 'That\'s a great deal!' },
                { word: 'defective', type: 'adj', pronunciation: '/dɪˈfektɪv/', meaning: 'Bị lỗi', example: 'This product is defective.' },
                { word: 'delivery', type: 'noun', pronunciation: '/dɪˈlɪvəri/', meaning: 'Giao hàng', example: 'Free delivery on orders over $50.' },
                { word: 'display', type: 'noun', pronunciation: '/dɪˈspleɪ/', meaning: 'Trưng bày', example: 'The items are on display.' },
                { word: 'expiration', type: 'noun', pronunciation: '/ˌekspəˈreɪʃn/', meaning: 'Hạn sử dụng', example: 'Check the expiration date.' },
                { word: 'fitting room', type: 'noun', pronunciation: '/ˈfɪtɪŋ ruːm/', meaning: 'Phòng thay đồ', example: 'The fitting rooms are over there.' },
                { word: 'inventory', type: 'noun', pronunciation: '/ˈɪnvəntɔːri/', meaning: 'Hàng tồn kho', example: 'We need to check our inventory.' },
                { word: 'merchandise', type: 'noun', pronunciation: '/ˈmɜːrtʃəndaɪz/', meaning: 'Hàng hóa', example: 'New merchandise arrives weekly.' },
                { word: 'outlet', type: 'noun', pronunciation: '/ˈaʊtlet/', meaning: 'Cửa hàng bán lẻ', example: 'There\'s an outlet mall nearby.' },
                { word: 'product', type: 'noun', pronunciation: '/ˈprɑːdʌkt/', meaning: 'Sản phẩm', example: 'This product is very popular.' },
                { word: 'promotion', type: 'noun', pronunciation: '/prəˈmoʊʃn/', meaning: 'Khuyến mãi', example: 'There\'s a promotion this week.' },
                { word: 'quality', type: 'noun', pronunciation: '/ˈkwɑːləti/', meaning: 'Chất lượng', example: 'The quality is excellent.' },
                { word: 'replacement', type: 'noun', pronunciation: '/rɪˈpleɪsmənt/', meaning: 'Thay thế', example: 'Can I get a replacement?' },
                { word: 'selection', type: 'noun', pronunciation: '/sɪˈlekʃn/', meaning: 'Sự lựa chọn', example: 'They have a great selection.' },
                { word: 'shelf', type: 'noun', pronunciation: '/ʃelf/', meaning: 'Kệ', example: 'The books are on the top shelf.' },
                { word: 'shipment', type: 'noun', pronunciation: '/ˈʃɪpmənt/', meaning: 'Lô hàng', example: 'The shipment arrives tomorrow.' },
                { word: 'size', type: 'noun', pronunciation: '/saɪz/', meaning: 'Kích cỡ', example: 'What size do you wear?' },
                { word: 'supplier', type: 'noun', pronunciation: '/səˈplaɪər/', meaning: 'Nhà cung cấp', example: 'We need a new supplier.' },
                { word: 'transaction', type: 'noun', pronunciation: '/trænˈzækʃn/', meaning: 'Giao dịch', example: 'The transaction was successful.' },
                { word: 'vendor', type: 'noun', pronunciation: '/ˈvendər/', meaning: 'Người bán hàng', example: 'Street vendors sell local crafts.' }
            ]
        },
        {
            id: 'technology-internet',
            name: 'Technology & Internet',
            icon: '💻',
            description: 'Từ vựng công nghệ và internet',
            words: [
                { word: 'access', type: 'verb', pronunciation: '/ˈækses/', meaning: 'Truy cập', example: 'You can access the files online.' },
                { word: 'application', type: 'noun', pronunciation: '/ˌæplɪˈkeɪʃn/', meaning: 'Ứng dụng', example: 'Download the application from our website.' },
                { word: 'browse', type: 'verb', pronunciation: '/braʊz/', meaning: 'Duyệt web', example: 'I was browsing the internet.' },
                { word: 'connect', type: 'verb', pronunciation: '/kəˈnekt/', meaning: 'Kết nối', example: 'Please connect to the Wi-Fi.' },
                { word: 'database', type: 'noun', pronunciation: '/ˈdeɪtəbeɪs/', meaning: 'Cơ sở dữ liệu', example: 'All information is stored in the database.' },
                { word: 'device', type: 'noun', pronunciation: '/dɪˈvaɪs/', meaning: 'Thiết bị', example: 'This app works on all devices.' },
                { word: 'download', type: 'verb', pronunciation: '/ˌdaʊnˈloʊd/', meaning: 'Tải xuống', example: 'You can download the file here.' },
                { word: 'email', type: 'noun', pronunciation: '/ˈiːmeɪl/', meaning: 'Thư điện tử', example: 'Send me an email with the details.' },
                { word: 'install', type: 'verb', pronunciation: '/ɪnˈstɔːl/', meaning: 'Cài đặt', example: 'You need to install the software first.' },
                { word: 'internet', type: 'noun', pronunciation: '/ˈɪntərnet/', meaning: 'Mạng internet', example: 'Do you have internet access?' },
                { word: 'network', type: 'noun', pronunciation: '/ˈnetwɜːrk/', meaning: 'Mạng lưới', example: 'Join our professional network.' },
                { word: 'online', type: 'adj', pronunciation: '/ˌɑːnˈlaɪn/', meaning: 'Trực tuyến', example: 'You can shop online 24/7.' },
                { word: 'password', type: 'noun', pronunciation: '/ˈpæswɜːrd/', meaning: 'Mật khẩu', example: 'Please enter your password.' },
                { word: 'software', type: 'noun', pronunciation: '/ˈsɔːftwer/', meaning: 'Phần mềm', example: 'We need to update the software.' },
                { word: 'system', type: 'noun', pronunciation: '/ˈsɪstəm/', meaning: 'Hệ thống', example: 'The system is down for maintenance.' },
                { word: 'update', type: 'verb', pronunciation: '/ʌpˈdeɪt/', meaning: 'Cập nhật', example: 'Please update your profile.' },
                { word: 'upload', type: 'verb', pronunciation: '/ˌʌpˈloʊd/', meaning: 'Tải lên', example: 'You can upload photos to the cloud.' },
                { word: 'user', type: 'noun', pronunciation: '/ˈjuːzər/', meaning: 'Người dùng', example: 'How many users do you have?' },
                { word: 'website', type: 'noun', pronunciation: '/ˈwebsaɪt/', meaning: 'Trang web', example: 'Visit our website for more information.' },
                { word: 'wireless', type: 'adj', pronunciation: '/ˈwaɪərləs/', meaning: 'Không dây', example: 'The room has wireless internet.' },
                { word: 'algorithm', type: 'noun', pronunciation: '/ˈælɡərɪðəm/', meaning: 'Thuật toán', example: 'The algorithm processes data quickly.' },
                { word: 'backup', type: 'noun', pronunciation: '/ˈbækʌp/', meaning: 'Sao lưu', example: 'Always create a backup of your files.' },
                { word: 'bandwidth', type: 'noun', pronunciation: '/ˈbændwɪdθ/', meaning: 'Băng thông', example: 'We need more bandwidth for video calls.' },
                { word: 'browser', type: 'noun', pronunciation: '/ˈbraʊzər/', meaning: 'Trình duyệt', example: 'Which browser do you use?' },
                { word: 'cache', type: 'noun', pronunciation: '/kæʃ/', meaning: 'Bộ nhớ đệm', example: 'Clear your browser cache.' },
                { word: 'click', type: 'verb', pronunciation: '/klɪk/', meaning: 'Nhấp chuột', example: 'Click here to continue.' },
                { word: 'cloud', type: 'noun', pronunciation: '/klaʊd/', meaning: 'Đám mây (lưu trữ)', example: 'Files are stored in the cloud.' },
                { word: 'compatible', type: 'adj', pronunciation: '/kəmˈpætəbl/', meaning: 'Tương thích', example: 'Is this compatible with Mac?' },
                { word: 'configure', type: 'verb', pronunciation: '/kənˈfɪɡjər/', meaning: 'Cấu hình', example: 'You need to configure your settings.' },
                { word: 'crash', type: 'verb', pronunciation: '/kræʃ/', meaning: 'Bị treo, bị sập', example: 'My computer crashed.' },
                { word: 'delete', type: 'verb', pronunciation: '/dɪˈliːt/', meaning: 'Xóa', example: 'Delete the old files.' },
                { word: 'digital', type: 'adj', pronunciation: '/ˈdɪdʒɪtl/', meaning: 'Kỹ thuật số', example: 'We live in a digital age.' },
                { word: 'display', type: 'noun', pronunciation: '/dɪˈspleɪ/', meaning: 'Màn hình hiển thị', example: 'The display is very clear.' },
                { word: 'encrypt', type: 'verb', pronunciation: '/ɪnˈkrɪpt/', meaning: 'Mã hóa', example: 'All data is encrypted.' },
                { word: 'error', type: 'noun', pronunciation: '/ˈerər/', meaning: 'Lỗi', example: 'I got an error message.' },
                { word: 'file', type: 'noun', pronunciation: '/faɪl/', meaning: 'Tập tin', example: 'Save the file to your desktop.' },
                { word: 'firewall', type: 'noun', pronunciation: '/ˈfaɪərwɔːl/', meaning: 'Tường lửa', example: 'The firewall blocked the attack.' },
                { word: 'format', type: 'verb', pronunciation: '/ˈfɔːrmæt/', meaning: 'Định dạng', example: 'Format the document properly.' },
                { word: 'hardware', type: 'noun', pronunciation: '/ˈhɑːrdwer/', meaning: 'Phần cứng', example: 'The hardware needs upgrading.' },
                { word: 'icon', type: 'noun', pronunciation: '/ˈaɪkɑːn/', meaning: 'Biểu tượng', example: 'Click on this icon.' },
                { word: 'keyboard', type: 'noun', pronunciation: '/ˈkiːbɔːrd/', meaning: 'Bàn phím', example: 'The keyboard is not working.' },
                { word: 'link', type: 'noun', pronunciation: '/lɪŋk/', meaning: 'Liên kết', example: 'Click on the link.' },
                { word: 'malware', type: 'noun', pronunciation: '/ˈmælwer/', meaning: 'Phần mềm độc hại', example: 'Install antivirus to protect against malware.' },
                { word: 'memory', type: 'noun', pronunciation: '/ˈmeməri/', meaning: 'Bộ nhớ', example: 'This computer has 16GB of memory.' },
                { word: 'monitor', type: 'noun', pronunciation: '/ˈmɑːnɪtər/', meaning: 'Màn hình', example: 'I need a larger monitor.' },
                { word: 'server', type: 'noun', pronunciation: '/ˈsɜːrvər/', meaning: 'Máy chủ', example: 'The server is down.' },
                { word: 'spam', type: 'noun', pronunciation: '/spæm/', meaning: 'Thư rác', example: 'This email went to spam.' },
                { word: 'storage', type: 'noun', pronunciation: '/ˈstɔːrɪdʒ/', meaning: 'Lưu trữ', example: 'Cloud storage is convenient.' },
                { word: 'virus', type: 'noun', pronunciation: '/ˈvaɪrəs/', meaning: 'Vi-rút', example: 'The computer has a virus.' }
            ]
        },
        {
            id: 'employment-recruitment',
            name: 'Employment & Recruitment',
            icon: '👔',
            description: 'Từ vựng tuyển dụng và việc làm',
            words: [
                { word: 'advertise', type: 'verb', pronunciation: '/ˈædvərtaɪz/', meaning: 'Quảng cáo', example: 'We advertised the job online.' },
                { word: 'applicant', type: 'noun', pronunciation: '/ˈæplɪkənt/', meaning: 'Ứng viên', example: 'We received 50 applicants for the position.' },
                { word: 'apply', type: 'verb', pronunciation: '/əˈplaɪ/', meaning: 'Nộp đơn, ứng tuyển', example: 'I want to apply for this job.' },
                { word: 'benefit', type: 'noun', pronunciation: '/ˈbenɪfɪt/', meaning: 'Phúc lợi', example: 'The job comes with great benefits.' },
                { word: 'candidate', type: 'noun', pronunciation: '/ˈkændɪdət/', meaning: 'Ứng cử viên', example: 'She is a strong candidate for the position.' },
                { word: 'career', type: 'noun', pronunciation: '/kəˈrɪr/', meaning: 'Sự nghiệp', example: 'I want to build a career in marketing.' },
                { word: 'employ', type: 'verb', pronunciation: '/ɪmˈplɔɪ/', meaning: 'Tuyển dụng', example: 'The company employs 500 people.' },
                { word: 'employer', type: 'noun', pronunciation: '/ɪmˈplɔɪər/', meaning: 'Nhà tuyển dụng', example: 'My employer offers flexible working hours.' },
                { word: 'experience', type: 'noun', pronunciation: '/ɪkˈspɪriəns/', meaning: 'Kinh nghiệm', example: 'Do you have any work experience?' },
                { word: 'hire', type: 'verb', pronunciation: '/ˈhaɪər/', meaning: 'Thuê, tuyển dụng', example: 'We plan to hire five new staff members.' },
                { word: 'interview', type: 'noun', pronunciation: '/ˈɪntərvjuː/', meaning: 'Phỏng vấn', example: 'I have a job interview tomorrow.' },
                { word: 'position', type: 'noun', pronunciation: '/pəˈzɪʃn/', meaning: 'Vị trí, chức vụ', example: 'This is a full-time position.' },
                { word: 'promote', type: 'verb', pronunciation: '/prəˈmoʊt/', meaning: 'Thăng chức', example: 'She was promoted to manager.' },
                { word: 'qualification', type: 'noun', pronunciation: '/ˌkwɑːlɪfɪˈkeɪʃn/', meaning: 'Bằng cấp, trình độ', example: 'What qualifications do you have?' },
                { word: 'recruit', type: 'verb', pronunciation: '/rɪˈkruːt/', meaning: 'Tuyển dụng', example: 'We are recruiting new graduates.' },
                { word: 'resign', type: 'verb', pronunciation: '/rɪˈzaɪn/', meaning: 'Từ chức', example: 'He resigned from his position last month.' },
                { word: 'resume', type: 'noun', pronunciation: '/rɪˈzuːmeɪ/', meaning: 'Sơ yếu lý lịch', example: 'Please submit your resume by email.' },
                { word: 'salary', type: 'noun', pronunciation: '/ˈsæləri/', meaning: 'Lương', example: 'What is the starting salary?' },
                { word: 'skill', type: 'noun', pronunciation: '/skɪl/', meaning: 'Kỹ năng', example: 'Communication skills are essential.' },
                { word: 'vacant', type: 'adj', pronunciation: '/ˈveɪkənt/', meaning: 'Còn trống', example: 'We have a vacant position in sales.' },
                { word: 'training', type: 'noun', pronunciation: '/ˈtreɪnɪŋ/', meaning: 'Đào tạo', example: 'All new employees receive training.' },
                { word: 'workforce', type: 'noun', pronunciation: '/ˈwɜːrkfɔːrs/', meaning: 'Lực lượng lao động', example: 'The company has a diverse workforce.' },
                { word: 'probation', type: 'noun', pronunciation: '/proʊˈbeɪʃn/', meaning: 'Thử việc', example: 'There is a three-month probation period.' },
                { word: 'permanent', type: 'adj', pronunciation: '/ˈpɜːrmənənt/', meaning: 'Vĩnh viễn, cố định', example: 'This is a permanent position.' },
                { word: 'temporary', type: 'adj', pronunciation: '/ˈtempəreri/', meaning: 'Tạm thời', example: 'We need temporary staff for summer.' },
                { word: 'part-time', type: 'adj', pronunciation: '/ˌpɑːrt ˈtaɪm/', meaning: 'Bán thời gian', example: 'She works part-time.' },
                { word: 'full-time', type: 'adj', pronunciation: '/ˌfʊl ˈtaɪm/', meaning: 'Toàn thời gian', example: 'This is a full-time job.' },
                { word: 'contract', type: 'noun', pronunciation: '/ˈkɑːntrækt/', meaning: 'Hợp đồng', example: 'Sign the employment contract.' },
                { word: 'overtime', type: 'noun', pronunciation: '/ˈoʊvərtaɪm/', meaning: 'Làm thêm giờ', example: 'You will be paid for overtime.' },
                { word: 'reference', type: 'noun', pronunciation: '/ˈrefrəns/', meaning: 'Người giới thiệu', example: 'Please provide two references.' },
                { word: 'achievements', type: 'noun', pronunciation: '/əˈtʃiːvmənts/', meaning: 'Thành tích', example: 'List your achievements on your resume.' },
                { word: 'deadline', type: 'noun', pronunciation: '/ˈdedlaɪn/', meaning: 'Hạn cuối', example: 'The application deadline is Friday.' },
                { word: 'fired', type: 'adj', pronunciation: '/ˈfaɪərd/', meaning: 'Bị sa thải', example: 'He was fired for poor performance.' },
                { word: 'laid off', type: 'verb', pronunciation: '/leɪd ɔːf/', meaning: 'Bị cho nghỉ việc (cắt giảm)', example: 'Many workers were laid off.' },
                { word: 'bonus', type: 'noun', pronunciation: '/ˈboʊnəs/', meaning: 'Tiền thưởng', example: 'Employees receive an annual bonus.' },
                { word: 'commission', type: 'noun', pronunciation: '/kəˈmɪʃn/', meaning: 'Hoa hồng', example: 'Sales staff earn commission.' },
                { word: 'benefits package', type: 'noun', pronunciation: '/ˈbenɪfɪts ˈpækɪdʒ/', meaning: 'Gói phúc lợi', example: 'The benefits package includes health insurance.' },
                { word: 'retirement', type: 'noun', pronunciation: '/rɪˈtaɪərmənt/', meaning: 'Về hưu', example: 'The company offers a retirement plan.' },
                { word: 'apprentice', type: 'noun', pronunciation: '/əˈprentɪs/', meaning: 'Người học việc', example: 'She started as an apprentice.' },
                { word: 'intern', type: 'noun', pronunciation: '/ˈɪntɜːrn/', meaning: 'Thực tập sinh', example: 'We have three interns this summer.' },
                { word: 'colleague', type: 'noun', pronunciation: '/ˈkɑːliːɡ/', meaning: 'Đồng nghiệp', example: 'My colleagues are very supportive.' },
                { word: 'supervisor', type: 'noun', pronunciation: '/ˈsuːpərvaɪzər/', meaning: 'Người giám sát', example: 'Report to your supervisor.' },
                { word: 'headhunter', type: 'noun', pronunciation: '/ˈhedhʌntər/', meaning: 'Người tuyển dụng chuyên nghiệp', example: 'A headhunter contacted me about a job.' },
                { word: 'probationary', type: 'adj', pronunciation: '/proʊˈbeɪʃəneri/', meaning: 'Thử việc', example: 'You are on probationary period.' },
                { word: 'shift', type: 'noun', pronunciation: '/ʃɪft/', meaning: 'Ca làm việc', example: 'I work the night shift.' },
                { word: 'credentials', type: 'noun', pronunciation: '/krɪˈdenʃlz/', meaning: 'Bằng cấp, chứng chỉ', example: 'Please bring your credentials to the interview.' },
                { word: 'portfolio', type: 'noun', pronunciation: '/pɔːrtˈfoʊlioʊ/', meaning: 'Hồ sơ năng lực', example: 'Show us your design portfolio.' }
            ]
        },
        {
            id: 'health-wellness',
            name: 'Health & Wellness',
            icon: '🏥',
            description: 'Từ vựng y tế và sức khỏe',
            words: [
                { word: 'appointment', type: 'noun', pronunciation: '/əˈpɔɪntmənt/', meaning: 'Cuộc hẹn', example: 'I have a doctor\'s appointment at 3 PM.' },
                { word: 'checkup', type: 'noun', pronunciation: '/ˈtʃekʌp/', meaning: 'Khám sức khỏe', example: 'You should get a regular checkup.' },
                { word: 'clinic', type: 'noun', pronunciation: '/ˈklɪnɪk/', meaning: 'Phòng khám', example: 'The clinic is open on weekdays.' },
                { word: 'diagnosis', type: 'noun', pronunciation: '/ˌdaɪəɡˈnoʊsɪs/', meaning: 'Chẩn đoán', example: 'The doctor made a quick diagnosis.' },
                { word: 'examine', type: 'verb', pronunciation: '/ɪɡˈzæmɪn/', meaning: 'Khám, kiểm tra', example: 'The doctor will examine you now.' },
                { word: 'exercise', type: 'noun', pronunciation: '/ˈeksərsaɪz/', meaning: 'Tập thể dục', example: 'Regular exercise is important for health.' },
                { word: 'fitness', type: 'noun', pronunciation: '/ˈfɪtnəs/', meaning: 'Thể lực, thể dục', example: 'She joined a fitness center.' },
                { word: 'healthy', type: 'adj', pronunciation: '/ˈhelθi/', meaning: 'Khỏe mạnh', example: 'Eating vegetables is healthy.' },
                { word: 'hospital', type: 'noun', pronunciation: '/ˈhɑːspɪtl/', meaning: 'Bệnh viện', example: 'He was taken to the hospital.' },
                { word: 'illness', type: 'noun', pronunciation: '/ˈɪlnəs/', meaning: 'Bệnh tật', example: 'She recovered from her illness.' },
                { word: 'insurance', type: 'noun', pronunciation: '/ɪnˈʃʊrəns/', meaning: 'Bảo hiểm', example: 'Do you have health insurance?' },
                { word: 'medicine', type: 'noun', pronunciation: '/ˈmedɪsn/', meaning: 'Thuốc', example: 'Take this medicine twice a day.' },
                { word: 'nutrition', type: 'noun', pronunciation: '/nuːˈtrɪʃn/', meaning: 'Dinh dưỡng', example: 'Good nutrition is essential for health.' },
                { word: 'patient', type: 'noun', pronunciation: '/ˈpeɪʃnt/', meaning: 'Bệnh nhân', example: 'The patient is recovering well.' },
                { word: 'prescription', type: 'noun', pronunciation: '/prɪˈskrɪpʃn/', meaning: 'Đơn thuốc', example: 'I need to fill this prescription.' },
                { word: 'prevent', type: 'verb', pronunciation: '/prɪˈvent/', meaning: 'Ngăn ngừa', example: 'Vaccination can prevent diseases.' },
                { word: 'symptom', type: 'noun', pronunciation: '/ˈsɪmptəm/', meaning: 'Triệu chứng', example: 'What are your symptoms?' },
                { word: 'therapy', type: 'noun', pronunciation: '/ˈθerəpi/', meaning: 'Điều trị, trị liệu', example: 'He is undergoing physical therapy.' },
                { word: 'treatment', type: 'noun', pronunciation: '/ˈtriːtmənt/', meaning: 'Sự điều trị', example: 'The treatment was successful.' },
                { word: 'wellness', type: 'noun', pronunciation: '/ˈwelnəs/', meaning: 'Sức khỏe tốt', example: 'The company promotes employee wellness.' },
                { word: 'allergic', type: 'adj', pronunciation: '/əˈlɜːrdʒɪk/', meaning: 'Dị ứng', example: 'I am allergic to peanuts.' },
                { word: 'vaccination', type: 'noun', pronunciation: '/ˌvæksɪˈneɪʃn/', meaning: 'Tiêm chủng', example: 'Annual flu vaccination is recommended.' },
                { word: 'recovery', type: 'noun', pronunciation: '/rɪˈkʌvəri/', meaning: 'Sự hồi phục', example: 'She made a full recovery.' },
                { word: 'emergency', type: 'noun', pronunciation: '/ɪˈmɜːrdʒənsi/', meaning: 'Cấp cứu', example: 'Call 911 in case of emergency.' },
                { word: 'surgery', type: 'noun', pronunciation: '/ˈsɜːrdʒəri/', meaning: 'Phẫu thuật', example: 'He needs surgery next week.' },
                { word: 'injury', type: 'noun', pronunciation: '/ˈɪndʒəri/', meaning: 'Chấn thương', example: 'Sports injuries are common.' },
                { word: 'physician', type: 'noun', pronunciation: '/fɪˈzɪʃn/', meaning: 'Bác sĩ', example: 'Consult your physician before starting.' },
                { word: 'disease', type: 'noun', pronunciation: '/dɪˈziːz/', meaning: 'Bệnh tật', example: 'Preventable diseases can be avoided.' },
                { word: 'chronic', type: 'adj', pronunciation: '/ˈkrɑːnɪk/', meaning: 'Mãn tính', example: 'He has chronic back pain.' },
                { word: 'acute', type: 'adj', pronunciation: '/əˈkjuːt/', meaning: 'Cấp tính', example: 'Acute pain requires immediate attention.' },
                { word: 'mental', type: 'adj', pronunciation: '/ˈmentl/', meaning: 'Tinh thần', example: 'Mental health is important.' },
                { word: 'physical', type: 'adj', pronunciation: '/ˈfɪzɪkl/', meaning: 'Thể chất', example: 'Regular physical activity is beneficial.' },
                { word: 'stress', type: 'noun', pronunciation: '/stres/', meaning: 'Căng thẳng', example: 'Stress can affect your health.' },
                { word: 'fatigue', type: 'noun', pronunciation: '/fəˈtiːɡ/', meaning: 'Mệt mỏi', example: 'Fatigue is a common symptom.' },
                { word: 'diet', type: 'noun', pronunciation: '/ˈdaɪət/', meaning: 'Chế độ ăn', example: 'A balanced diet is essential.' },
                { word: 'vitamin', type: 'noun', pronunciation: '/ˈvaɪtəmɪn/', meaning: 'Vitamin', example: 'Take vitamin supplements daily.' },
                { word: 'supplement', type: 'noun', pronunciation: '/ˈsʌplɪmənt/', meaning: 'Chất bổ sung', example: 'Dietary supplements can help.' },
                { word: 'breathing', type: 'noun', pronunciation: '/ˈbriːðɪŋ/', meaning: 'Hơi thở', example: 'Deep breathing helps relaxation.' },
                { word: 'pulse', type: 'noun', pronunciation: '/pʌls/', meaning: 'Mạch', example: 'The nurse checked my pulse.' },
                { word: 'fever', type: 'noun', pronunciation: '/ˈfiːvər/', meaning: 'Sốt', example: 'He has a high fever.' },
                { word: 'cough', type: 'noun', pronunciation: '/kɔːf/', meaning: 'Ho', example: 'A persistent cough needs checking.' },
                { word: 'sneeze', type: 'verb', pronunciation: '/sniːz/', meaning: 'Hắt hơi', example: 'Cover your mouth when you sneeze.' },
                { word: 'headache', type: 'noun', pronunciation: '/ˈhedeɪk/', meaning: 'Đau đầu', example: 'I have a terrible headache.' },
                { word: 'dizzy', type: 'adj', pronunciation: '/ˈdɪzi/', meaning: 'Chóng mặt', example: 'I feel dizzy when I stand up.' },
                { word: 'nausea', type: 'noun', pronunciation: '/ˈnɔːziə/', meaning: 'Buồn nôn', example: 'The medicine caused nausea.' },
                { word: 'pain', type: 'noun', pronunciation: '/peɪn/', meaning: 'Đau', example: 'He complained of chest pain.' },
                { word: 'swelling', type: 'noun', pronunciation: '/ˈswelɪŋ/', meaning: 'Sưng', example: 'Apply ice to reduce swelling.' },
                { word: 'bandage', type: 'noun', pronunciation: '/ˈbændɪdʒ/', meaning: 'Băng', example: 'Put a bandage on the wound.' },
                { word: 'infection', type: 'noun', pronunciation: '/ɪnˈfekʃn/', meaning: 'Nhiễm trùng', example: 'The infection spread quickly.' }
            ]
        },
        {
            id: 'meetings-presentations',
            name: 'Meetings & Presentations',
            icon: '📊',
            description: 'Từ vựng họp và thuyết trình',
            words: [
                { word: 'attend', type: 'verb', pronunciation: '/əˈtend/', meaning: 'Tham dự', example: 'Will you attend the meeting?' },
                { word: 'audience', type: 'noun', pronunciation: '/ˈɔːdiəns/', meaning: 'Khán giả, thính giả', example: 'The audience asked many questions.' },
                { word: 'chairman', type: 'noun', pronunciation: '/ˈtʃermən/', meaning: 'Chủ tọa', example: 'The chairman opened the meeting.' },
                { word: 'chart', type: 'noun', pronunciation: '/tʃɑːrt/', meaning: 'Biểu đồ', example: 'The chart shows our sales growth.' },
                { word: 'clarify', type: 'verb', pronunciation: '/ˈklærəfaɪ/', meaning: 'Làm rõ, giải thích', example: 'Could you clarify that point?' },
                { word: 'conclude', type: 'verb', pronunciation: '/kənˈkluːd/', meaning: 'Kết luận', example: 'Let me conclude by saying thank you.' },
                { word: 'discuss', type: 'verb', pronunciation: '/dɪˈskʌs/', meaning: 'Thảo luận', example: 'We need to discuss this issue.' },
                { word: 'distribute', type: 'verb', pronunciation: '/dɪˈstrɪbjuːt/', meaning: 'Phân phát', example: 'Please distribute these handouts.' },
                { word: 'graph', type: 'noun', pronunciation: '/ɡræf/', meaning: 'Đồ thị', example: 'The graph illustrates the trend.' },
                { word: 'handout', type: 'noun', pronunciation: '/ˈhændaʊt/', meaning: 'Tài liệu phát tay', example: 'Everyone received a handout.' },
                { word: 'introduce', type: 'verb', pronunciation: '/ˌɪntrəˈduːs/', meaning: 'Giới thiệu', example: 'Let me introduce our guest speaker.' },
                { word: 'minutes', type: 'noun', pronunciation: '/ˈmɪnɪts/', meaning: 'Biên bản họp', example: 'Who will take the minutes?' },
                { word: 'participate', type: 'verb', pronunciation: '/pɑːrˈtɪsɪpeɪt/', meaning: 'Tham gia', example: 'Everyone should participate in the discussion.' },
                { word: 'postpone', type: 'verb', pronunciation: '/poʊstˈpoʊn/', meaning: 'Hoãn lại', example: 'We had to postpone the meeting.' },
                { word: 'present', type: 'verb', pronunciation: '/prɪˈzent/', meaning: 'Trình bày', example: 'I will present the quarterly results.' },
                { word: 'proposal', type: 'noun', pronunciation: '/prəˈpoʊzl/', meaning: 'Đề xuất', example: 'We submitted a proposal to the board.' },
                { word: 'schedule', type: 'verb', pronunciation: '/ˈskedʒuːl/', meaning: 'Lên lịch', example: 'The meeting is scheduled for Tuesday.' },
                { word: 'slide', type: 'noun', pronunciation: '/slaɪd/', meaning: 'Slide trình chiếu', example: 'Please turn to the next slide.' },
                { word: 'summarize', type: 'verb', pronunciation: '/ˈsʌməraɪz/', meaning: 'Tóm tắt', example: 'Let me summarize the main points.' },
                { word: 'venue', type: 'noun', pronunciation: '/ˈvenjuː/', meaning: 'Địa điểm', example: 'What is the venue for the conference?' },
                { word: 'podium', type: 'noun', pronunciation: '/ˈpoʊdiəm/', meaning: 'Bục phát biểu', example: 'He stood at the podium.' },
                { word: 'microphone', type: 'noun', pronunciation: '/ˈmaɪkrəfoʊn/', meaning: 'Micro', example: 'Please speak into the microphone.' },
                { word: 'projector', type: 'noun', pronunciation: '/prəˈdʒektər/', meaning: 'Máy chiếu', example: 'The projector is not working.' },
                { word: 'agenda item', type: 'noun', pronunciation: '/əˈdʒendə ˈaɪtəm/', meaning: 'Mục chương trình', example: 'Let\'s move to the next agenda item.' },
                { word: 'keynote', type: 'noun', pronunciation: '/ˈkiːnoʊt/', meaning: 'Bài phát biểu chính', example: 'She delivered the keynote speech.' },
                { word: 'seminar', type: 'noun', pronunciation: '/ˈsemɪnɑːr/', meaning: 'Hội thảo', example: 'I attended a marketing seminar.' },
                { word: 'workshop', type: 'noun', pronunciation: '/ˈwɜːrkʃɑːp/', meaning: 'Hội thảo thực hành', example: 'Join our leadership workshop.' },
                { word: 'brainstorm', type: 'verb', pronunciation: '/ˈbreɪnstɔːrm/', meaning: 'Động não', example: 'Let\'s brainstorm some ideas.' },
                { word: 'collaborate', type: 'verb', pronunciation: '/kəˈlæbəreɪt/', meaning: 'Cộng tác', example: 'We need to collaborate on this.' },
                { word: 'feedback', type: 'noun', pronunciation: '/ˈfiːdbæk/', meaning: 'Phản hồi', example: 'I appreciate your feedback.' },
                { word: 'opinion', type: 'noun', pronunciation: '/əˈpɪnjən/', meaning: 'Ý kiến', example: 'What is your opinion on this?' },
                { word: 'perspective', type: 'noun', pronunciation: '/pərˈspektɪv/', meaning: 'Quan điểm', example: 'Consider different perspectives.' },
                { word: 'deadline', type: 'noun', pronunciation: '/ˈdedlaɪn/', meaning: 'Thời hạn', example: 'We missed the deadline.' },
                { word: 'outcome', type: 'noun', pronunciation: '/ˈaʊtkʌm/', meaning: 'Kết quả', example: 'The outcome was positive.' },
                { word: 'objective', type: 'noun', pronunciation: '/əbˈdʒektɪv/', meaning: 'Mục tiêu', example: 'Our main objective is growth.' },
                { word: 'strategy', type: 'noun', pronunciation: '/ˈstrætədʒi/', meaning: 'Chiến lược', example: 'We need a new marketing strategy.' },
                { word: 'resolution', type: 'noun', pronunciation: '/ˌrezəˈluːʃn/', meaning: 'Quyết định, giải pháp', example: 'The board passed a resolution.' },
                { word: 'motion', type: 'noun', pronunciation: '/ˈmoʊʃn/', meaning: 'Kiến nghị', example: 'I second the motion.' },
                { word: 'adjourn', type: 'verb', pronunciation: '/əˈdʒɜːrn/', meaning: 'Hoãn (cuộc họp)', example: 'The meeting is adjourned.' },
                { word: 'quorum', type: 'noun', pronunciation: '/ˈkwɔːrəm/', meaning: 'Số lượng tối thiểu', example: 'We don\'t have a quorum.' },
                { word: 'vote', type: 'verb', pronunciation: '/voʊt/', meaning: 'Bỏ phiếu', example: 'Let\'s vote on this issue.' },
                { word: 'consensus', type: 'noun', pronunciation: '/kənˈsensəs/', meaning: 'Sự đồng thuận', example: 'We reached a consensus.' },
                { word: 'debate', type: 'noun', pronunciation: '/dɪˈbeɪt/', meaning: 'Tranh luận', example: 'There was a heated debate.' },
                { word: 'followup', type: 'noun', pronunciation: '/ˈfɑːloʊʌp/', meaning: 'Theo dõi sau', example: 'Schedule a followup meeting.' },
                { word: 'deliverable', type: 'noun', pronunciation: '/dɪˈlɪvərəbl/', meaning: 'Sản phẩm giao nộp', example: 'What are the project deliverables?' },
                { word: 'milestone', type: 'noun', pronunciation: '/ˈmaɪlstoʊn/', meaning: 'Cột mốc', example: 'We reached an important milestone.' },
                { word: 'action item', type: 'noun', pronunciation: '/ˈækʃn ˈaɪtəm/', meaning: 'Nhiệm vụ cần làm', example: 'Review all action items.' }
            ]
        },
        {
            id: 'communication-media',
            name: 'Communication & Media',
            icon: '📱',
            description: 'Từ vựng giao tiếp và truyền thông',
            words: [
                { word: 'advertise', type: 'verb', pronunciation: '/ˈædvərtaɪz/', meaning: 'Quảng cáo', example: 'They advertise on social media.' },
                { word: 'announcement', type: 'noun', pronunciation: '/əˈnaʊnsmənt/', meaning: 'Thông báo', example: 'There will be an important announcement.' },
                { word: 'article', type: 'noun', pronunciation: '/ˈɑːrtɪkl/', meaning: 'Bài báo', example: 'I read an interesting article today.' },
                { word: 'broadcast', type: 'verb', pronunciation: '/ˈbrɔːdkæst/', meaning: 'Phát sóng', example: 'The game will be broadcast live.' },
                { word: 'communicate', type: 'verb', pronunciation: '/kəˈmjuːnɪkeɪt/', meaning: 'Giao tiếp', example: 'We communicate via email.' },
                { word: 'contact', type: 'verb', pronunciation: '/ˈkɑːntækt/', meaning: 'Liên lạc', example: 'Please contact me if you have questions.' },
                { word: 'correspondent', type: 'noun', pronunciation: '/ˌkɔːrəˈspɑːndənt/', meaning: 'Phóng viên', example: 'Our correspondent is reporting live.' },
                { word: 'newsletter', type: 'noun', pronunciation: '/ˈnuːzletər/', meaning: 'Bản tin', example: 'Subscribe to our monthly newsletter.' },
                { word: 'notify', type: 'verb', pronunciation: '/ˈnoʊtɪfaɪ/', meaning: 'Thông báo', example: 'We will notify you by email.' },
                { word: 'post', type: 'verb', pronunciation: '/poʊst/', meaning: 'Đăng', example: 'She posted a photo on Instagram.' },
                { word: 'press', type: 'noun', pronunciation: '/pres/', meaning: 'Báo chí', example: 'The press was invited to the event.' },
                { word: 'public', type: 'adj', pronunciation: '/ˈpʌblɪk/', meaning: 'Công khai, công cộng', example: 'This is public information.' },
                { word: 'publish', type: 'verb', pronunciation: '/ˈpʌblɪʃ/', meaning: 'Xuất bản', example: 'The book was published last year.' },
                { word: 'reply', type: 'verb', pronunciation: '/rɪˈplaɪ/', meaning: 'Trả lời', example: 'Please reply to my email.' },
                { word: 'report', type: 'noun', pronunciation: '/rɪˈpɔːrt/', meaning: 'Báo cáo', example: 'I need to submit my report by Friday.' },
                { word: 'respond', type: 'verb', pronunciation: '/rɪˈspɑːnd/', meaning: 'Phản hồi', example: 'They responded quickly to our request.' },
                { word: 'social media', type: 'noun', pronunciation: '/ˈsoʊʃl ˈmiːdiə/', meaning: 'Mạng xã hội', example: 'We promote our products on social media.' },
                { word: 'subscribe', type: 'verb', pronunciation: '/səbˈskraɪb/', meaning: 'Đăng ký', example: 'Subscribe to our channel.' },
                { word: 'transmit', type: 'verb', pronunciation: '/trænsˈmɪt/', meaning: 'Truyền đi', example: 'The signal was transmitted worldwide.' },
                { word: 'update', type: 'noun', pronunciation: '/ˈʌpdeɪt/', meaning: 'Tin cập nhật', example: 'Check our website for updates.' },
                { word: 'media', type: 'noun', pronunciation: '/ˈmiːdiə/', meaning: 'Truyền thông', example: 'Social media is powerful.' },
                { word: 'advertising', type: 'noun', pronunciation: '/ˈædvərtaɪzɪŋ/', meaning: 'Quảng cáo', example: 'Advertising costs are rising.' },
                { word: 'campaign', type: 'noun', pronunciation: '/kæmˈpeɪn/', meaning: 'Chiến dịch', example: 'Launch a marketing campaign.' },
                { word: 'headline', type: 'noun', pronunciation: '/ˈhedlaɪn/', meaning: 'Tiêu đề', example: 'The headline caught my attention.' },
                { word: 'editor', type: 'noun', pronunciation: '/ˈedɪtər/', meaning: 'Biên tập viên', example: 'The editor approved the article.' },
                { word: 'journalist', type: 'noun', pronunciation: '/ˈdʒɜːrnəlɪst/', meaning: 'Nhà báo', example: 'She works as a journalist.' },
                { word: 'interview', type: 'verb', pronunciation: '/ˈɪntərvjuː/', meaning: 'Phỏng vấn', example: 'We interviewed several candidates.' },
                { word: 'coverage', type: 'noun', pronunciation: '/ˈkʌvərɪdʒ/', meaning: 'Sự đưa tin', example: 'Media coverage was extensive.' },
                { word: 'circulation', type: 'noun', pronunciation: '/ˌsɜːrkjəˈleɪʃn/', meaning: 'Lượng phát hành', example: 'The newspaper has high circulation.' },
                { word: 'subscription', type: 'noun', pronunciation: '/səbˈskrɪpʃn/', meaning: 'Đăng ký theo dõi', example: 'Renew your subscription today.' },
                { word: 'viral', type: 'adj', pronunciation: '/ˈvaɪrəl/', meaning: 'Lan truyền', example: 'The video went viral.' },
                { word: 'trending', type: 'adj', pronunciation: '/ˈtrendɪŋ/', meaning: 'Xu hướng', example: 'This topic is trending now.' },
                { word: 'follower', type: 'noun', pronunciation: '/ˈfɑːloʊər/', meaning: 'Người theo dõi', example: 'She has many followers.' },
                { word: 'platform', type: 'noun', pronunciation: '/ˈplætfɔːrm/', meaning: 'Nền tảng', example: 'Use multiple social platforms.' },
                { word: 'engagement', type: 'noun', pronunciation: '/ɪnˈɡeɪdʒmənt/', meaning: 'Tương tác', example: 'User engagement is increasing.' },
                { word: 'content', type: 'noun', pronunciation: '/ˈkɑːntent/', meaning: 'Nội dung', example: 'Create quality content.' },
                { word: 'influencer', type: 'noun', pronunciation: '/ˈɪnfluənsər/', meaning: 'Người có ảnh hưởng', example: 'Collaborate with influencers.' },
                { word: 'podcast', type: 'noun', pronunciation: '/ˈpɑːdkæst/', meaning: 'Podcast', example: 'Listen to our weekly podcast.' },
                { word: 'streaming', type: 'noun', pronunciation: '/ˈstriːmɪŋ/', meaning: 'Phát trực tiếp', example: 'Live streaming is popular.' },
                { word: 'upload', type: 'verb', pronunciation: '/ˌʌpˈloʊd/', meaning: 'Tải lên', example: 'Upload the video to YouTube.' },
                { word: 'download', type: 'verb', pronunciation: '/ˌdaʊnˈloʊd/', meaning: 'Tải xuống', example: 'Download the app for free.' },
                { word: 'hashtag', type: 'noun', pronunciation: '/ˈhæʃtæɡ/', meaning: 'Thẻ băm', example: 'Use relevant hashtags.' },
                { word: 'notification', type: 'noun', pronunciation: '/ˌnoʊtɪfɪˈkeɪʃn/', meaning: 'Thông báo', example: 'Turn on notifications.' },
                { word: 'comment', type: 'noun', pronunciation: '/ˈkɑːment/', meaning: 'Bình luận', example: 'Read the comments section.' },
                { word: 'share', type: 'verb', pronunciation: '/ʃer/', meaning: 'Chia sẻ', example: 'Share this post with friends.' },
                { word: 'like', type: 'verb', pronunciation: '/laɪk/', meaning: 'Thích', example: 'Like our page on Facebook.' },
                { word: 'message', type: 'noun', pronunciation: '/ˈmesɪdʒ/', meaning: 'Tin nhắn', example: 'Send me a message.' },
                { word: 'inbox', type: 'noun', pronunciation: '/ˈɪnbɑːks/', meaning: 'Hộp thư đến', example: 'Check your inbox daily.' }
            ]
        }
    ]
};

// Helper function to get random words from all topics
function getRandomWords(count) {
    const allWords = [];
    vocabularyData.topics.forEach(topic => {
        topic.words.forEach(word => {
            allWords.push({ ...word, topicName: topic.name });
        });
    });

    // Shuffle array
    for (let i = allWords.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [allWords[i], allWords[j]] = [allWords[j], allWords[i]];
    }

    return allWords.slice(0, count);
}

// Helper function to get topic by ID
function getTopicById(topicId) {
    return vocabularyData.topics.find(topic => topic.id === topicId);
}

// Calculate total word count
function getTotalWordCount() {
    return vocabularyData.topics.reduce((total, topic) => {
        return total + topic.words.length;
    }, 0);
}
